<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:ms-einstein-ai="http://www.mulesoft.org/schema/mule/ms-einstein-ai"
      xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
      xmlns:tls="http://www.mulesoft.org/schema/mule/tls"
      xsi:schemaLocation="
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
       http://www.mulesoft.org/schema/mule/tls http://www.mulesoft.org/schema/mule/tls/current/mule-tls.xsd
       http://www.mulesoft.org/schema/mule/ms-einstein-ai http://www.mulesoft.org/schema/mule/ms-einstein-ai/current/mule-ms-einstein-ai.xsd">

    <configuration-properties doc:name="Configuration properties" file="automation-credentials.properties"/>
    
    <ms-einstein-ai:config name="Einstein_Config" doc:name="Einstein Config" doc:id="e2310b9c-aa50-406c-85ae-8bfa200c009a">
        <ms-einstein-ai:oauth-client-credentials-connection connectionTimeout="60000">
            <ms-einstein-ai:oauth-client-credentials clientId="${config.client-id}" clientSecret="${config.client-secret}" tokenUrl="${config.salesforce-org}" />
        </ms-einstein-ai:oauth-client-credentials-connection>
    </ms-einstein-ai:config>

    <ms-einstein-ai:config name="Einstein_Config_Error" doc:name="Einstein Config Error" doc:id="e2310b9c-aa50-406c-85ae-8bfa200c009a" >
        <ms-einstein-ai:oauth-client-credentials-connection >
            <ms-einstein-ai:oauth-client-credentials clientId="testId" clientSecret="testSecret" tokenUrl="${config.salesforce-org}" />
        </ms-einstein-ai:oauth-client-credentials-connection>
    </ms-einstein-ai:config>

    <ms-einstein-ai:config name="Einstein_Config_TLS" doc:name="Einstein Config With TLS" doc:id="e2310b9c-aa50-406c-85ae-8bfa200c009a" >
        <ms-einstein-ai:oauth-client-credentials-connection connectionTimeout="60000">
            <tls:context >
                <tls:key-store type="jks" path="${m4-mutual-tls.keyStore}" keyPassword="${m4-mutual-tls.keyStorePassword}" password="${m4-mutual-tls.keyStorePassword}" />
            </tls:context>
            <ms-einstein-ai:oauth-client-credentials clientId="${config.client-id}" clientSecret="${config.client-secret}" tokenUrl="${config.salesforce-org}" />
        </ms-einstein-ai:oauth-client-credentials-connection>
    </ms-einstein-ai:config>

    <ms-einstein-ai:config name="Einstein_Config_Error_TLS" doc:name="Einstein Config Error With TLS" doc:id="e2310b9c-aa50-406c-85ae-8bfa200c009a" >
        <ms-einstein-ai:oauth-client-credentials-connection connectionTimeout="60000">
            <tls:context >
                <tls:key-store type="jks" path="${m4-mutual-tls.keyStore}" keyPassword="${m4-mutual-tls.keyStorePassword}" password="${m4-mutual-tls.keyStorePassword}" />
            </tls:context>
            <ms-einstein-ai:oauth-client-credentials clientId="testId" clientSecret="testSecret" tokenUrl="${config.salesforce-org}" />
        </ms-einstein-ai:oauth-client-credentials-connection>
    </ms-einstein-ai:config>
<!--
Commenting this code as cam tool does not support this proxy. Need some other public proxy server

    <ms-einstein-ai:config name="Einstein_Config_Proxy" doc:name="Einstein Config With Proxy" doc:id="e2310b9c-aa50-406c-85ae-8bfa200c009a" >
        <ms-einstein-ai:oauth-client-credentials-connection connectionTimeout="20" connectionTimeoutUnit="SECONDS" connectionIdleTimeout="20" connectionIdleTimeoutUnit="SECONDS">
            <ms-einstein-ai:proxy-config >
                <ms-einstein-ai:default-http-proxy-config host="${config.proxy-host}" port="${config.proxy-port}" username="${config.proxy-username}" password="${config.proxy-password}" />
            </ms-einstein-ai:proxy-config>
            <ms-einstein-ai:oauth-client-credentials clientId="${config.client-id}" clientSecret="${config.client-secret}" tokenUrl="${config.salesforce-org}" />
        </ms-einstein-ai:oauth-client-credentials-connection>
    </ms-einstein-ai:config>

    <ms-einstein-ai:config name="Einstein_Config_Error_Proxy" doc:name="Einstein Config With Proxy Error" doc:id="e2310b9c-aa50-406c-85ae-8bfa200c009a" >
        <ms-einstein-ai:oauth-client-credentials-connection connectionTimeout="20" connectionTimeoutUnit="SECONDS" connectionIdleTimeout="20" connectionIdleTimeoutUnit="SECONDS">
            <ms-einstein-ai:proxy-config >
                <ms-einstein-ai:default-http-proxy-config host="${config.proxy-host}" port="${config.proxy-port}" username="test" password="test" />
            </ms-einstein-ai:proxy-config>
            <ms-einstein-ai:oauth-client-credentials clientId="${config.client-id}" clientSecret="${config.client-secret}" tokenUrl="${config.salesforce-org}" />
        </ms-einstein-ai:oauth-client-credentials-connection>
    </ms-einstein-ai:config>
    -->

</mule>
